# Generated by Django 6.1 on 2026-08-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounter', '0002_basicinfomodel_bmr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfomodel',
            old_name='User',
            new_name='user',
        ),
    ]
